"""empty message

Revision ID: 220749e1b278
Revises: f61a7b92ace5
Create Date: 2024-12-13 21:35:07.393679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220749e1b278'
down_revision = 'f61a7b92ace5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_private')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_suspended')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
