"""empty message

Revision ID: 3589cf1f2453
Revises: 
Create Date: 2025-01-10 11:53:31.523916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3589cf1f2453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=True),
    sa.Column('following_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index('idx_post_created_at', ['post_id', 'id', 'created_at'], unique=False)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_like_post'), ['post'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_story'), ['story'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_user'), ['user'], unique=False)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('idx_user_created_at', ['user', 'id', 'created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_id', ['id'], unique=False)
        batch_op.create_index('idx_is_verified_active', ['is_verified', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_is_verified_active')
        batch_op.drop_index('idx_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('idx_user_created_at')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_like_user'))
        batch_op.drop_index(batch_op.f('ix_like_story'))
        batch_op.drop_index(batch_op.f('ix_like_post'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_post_created_at')

    op.drop_table('follow_request')
    # ### end Alembic commands ###
