"""empty message

Revision ID: 53b21ea4c4b7
Revises: 0c11af4850f1
Create Date: 2024-12-29 14:32:58.954981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53b21ea4c4b7'
down_revision = '0c11af4850f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=True),
    sa.Column('followed_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follow_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='follow_requests_followed_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='follow_requests_follower_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='follow_requests_pkey')
    )
    op.drop_table('follow_request')
    # ### end Alembic commands ###
