"""empty message

Revision ID: 65b0ab58c815
Revises: 94616213a3ed
Create Date: 2024-12-26 13:48:20.422215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b0ab58c815'
down_revision = '94616213a3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('story_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_owner', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'user', ['story_owner'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_view', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('story_owner')

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
