"""empty message

Revision ID: 6eca5a9a7d52
Revises: 90b2052e8e7d
Create Date: 2024-12-21 14:42:18.718391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eca5a9a7d52'
down_revision = '90b2052e8e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('follows_follower_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follows_following_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['following_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follows_following_id_fkey', 'user', ['following_id'], ['id'])
        batch_op.create_foreign_key('follows_follower_id_fkey', 'user', ['follower_id'], ['id'])

    # ### end Alembic commands ###
