"""empty message

Revision ID: 702f3795fa4e
Revises: e84dd115890d
Create Date: 2024-12-11 12:49:45.709622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702f3795fa4e'
down_revision = 'e84dd115890d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=15), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
