"""empty message

Revision ID: 95da32dce235
Revises: 6eca5a9a7d52
Create Date: 2024-12-24 11:09:19.384991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95da32dce235'
down_revision = '6eca5a9a7d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_social', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('other_social')

    # ### end Alembic commands ###
