"""empty message

Revision ID: fc0c468fa1c5
Revises: 53f70a097426
Create Date: 2024-11-29 14:43:21.229603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0c468fa1c5'
down_revision = '53f70a097426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist_token', schema=None) as batch_op:
        batch_op.drop_index('ix_blacklist_token_jti')
        batch_op.create_index(batch_op.f('ix_blacklist_token_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_token_jti'))
        batch_op.create_index('ix_blacklist_token_jti', ['jti'], unique=False)

    # ### end Alembic commands ###
