"""empty message

Revision ID: feee4805e309
Revises: 992946f34675
Create Date: 2024-12-09 13:27:33.366078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'feee4805e309'
down_revision = '992946f34675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
